version: '3.8'

services:
  schedule-api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.schedule-api.rule=Host(`api.schedule.vingp.dev`, `api.rsreu-schedule.ru`)"
      - "traefik.http.routers.schedule-api.entrypoints=http,https"
      - "traefik.http.routers.schedule-api.tls.certresolver=myresolver"
      - "traefik.http.services.schedule-api.loadbalancer.server.port=8081"
      - "traefik.http.routers.schedule-api.tls=true"
    networks:
      - traefik

networks:
  traefik:
    name: traefik-swarm
    external: true
