version: '3.8'


services:
  schedule-api:
    container_name: schedule-api
    build: .
    ports:
      - '8081:80'
    restart: always
    depends_on:
      - postgres
      - mongodb
    networks:
      - default
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=schedule_database
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - ENVIRONMENT=prod
      - OTL_ENDPOINT=tempo:4317

  mongodb:
    image: mongo:6.0.9
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always
    volumes:
      - mongodb_volume:/data/db
    networks:
      - default

  postgres:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "7433:5432"
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.11
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "31270:80"
    volumes:
      - pgadmin-data_volume:/var/lib/pgadmin
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
volumes:
  mongodb_volume:
  pgadmin-data_volume:
  postgres_data_volume:

networks:
  default:

