version: '3.8'


services:
  schedule-api:
    container_name: schedule-api
    build: .
    ports:
      - '8081:8081'
    restart: always
    networks:
      - default
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  mongodb:
    image: mongo:6.0.9
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always
    volumes:
      - mongodb_volume:/data/db
    networks:
      - default

volumes:
  mongodb_volume:

networks:
  default:
