// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/schedule/courses": {
            "get": {
                "description": "Курсы факультета",
                "tags": [
                    "Courses"
                ],
                "summary": "Get faculty courses",
                "parameters": [
                    {
                        "enum": [
                            "иэф",
                            "фаиту",
                            "фвт",
                            "фрт",
                            "фэ"
                        ],
                        "type": "string",
                        "description": "faculty",
                        "name": "faculty",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.FacultyCourses"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/day": {
            "get": {
                "description": "Информация о текущем дне",
                "tags": [
                    "Day"
                ],
                "summary": "Get day",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Day"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/faculties": {
            "get": {
                "description": "Факультеты",
                "tags": [
                    "Faculties"
                ],
                "summary": "Get faculties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Faculties"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/faculties/course": {
            "get": {
                "description": "Факультеты курса",
                "tags": [
                    "Faculties"
                ],
                "summary": "Get course faculties",
                "parameters": [
                    {
                        "enum": [
                            1,
                            2,
                            3,
                            4,
                            5
                        ],
                        "type": "integer",
                        "description": "course",
                        "name": "course",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.CourseFaculties"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/groups/sample": {
            "post": {
                "description": "Рассписание для нескольких групп",
                "tags": [
                    "Groups"
                ],
                "summary": "Get schedules by groups",
                "parameters": [
                    {
                        "description": "groups",
                        "name": "groups",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_handlers_v1.schedulesByGroupsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Schedule"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/groups/{group}": {
            "get": {
                "description": "Get schedule by group",
                "tags": [
                    "Groups"
                ],
                "summary": "Get schedule by group",
                "parameters": [
                    {
                        "type": "string",
                        "example": "344",
                        "description": "group",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Schedule"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/teachers": {
            "get": {
                "description": "Расписание преподавателя",
                "tags": [
                    "Teachers"
                ],
                "summary": "Get teacher schedule",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"Конюхов Алексей Николаевич\"",
                        "description": "teacher",
                        "name": "teacher",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherSchedule"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/schedule/teachers/all": {
            "get": {
                "description": "Список всех преподавателей",
                "tags": [
                    "Teachers"
                ],
                "summary": "Get teachers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeachersList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.CourseFaculties": {
            "type": "object",
            "properties": {
                "course": {
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ],
                    "example": 1
                },
                "faculties": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "иэф",
                            "фаиту",
                            "фвт",
                            "фрт",
                            "фэ"
                        ]
                    }
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.Day": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string",
                    "enum": [
                        "Monday",
                        "Tuesday",
                        "Wednesday",
                        "Thursday",
                        "Friday",
                        "Saturday",
                        "Sunday"
                    ],
                    "example": "Monday"
                },
                "day_ru": {
                    "type": "string",
                    "enum": [
                        "Пн",
                        "Вт",
                        "Ср",
                        "Чт",
                        "Пт",
                        "Сб",
                        "Вс"
                    ],
                    "example": "Пн"
                },
                "time": {
                    "type": "string",
                    "example": "08.10"
                },
                "week_type": {
                    "type": "string",
                    "enum": [
                        "числитель",
                        "знаменатель"
                    ],
                    "example": "знаменатель"
                },
                "week_type_eng": {
                    "type": "string",
                    "enum": [
                        "numerator",
                        "denominator"
                    ],
                    "example": "numerator"
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule": {
            "type": "object",
            "properties": {
                "lesson": {
                    "type": "string",
                    "example": "л.Высшая математика\nдоц.Конюхов А.Н.   333 С"
                },
                "time": {
                    "type": "string",
                    "example": "08.10-09.45"
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.Faculties": {
            "type": "object",
            "properties": {
                "faculties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.FacultyCourses": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "faculty": {
                    "type": "string",
                    "enum": [
                        "иэф",
                        "фаиту",
                        "фвт",
                        "фрт",
                        "фэ"
                    ],
                    "example": "фвт"
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.NumeratorDenominatorSchedule": {
            "type": "object",
            "properties": {
                "denominator": {
                    "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.WeekSchedule"
                },
                "numerator": {
                    "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.WeekSchedule"
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.Schedule": {
            "type": "object",
            "properties": {
                "course": {
                    "type": "integer",
                    "example": 1
                },
                "faculty": {
                    "type": "string",
                    "example": "фвт"
                },
                "file": {
                    "type": "string"
                },
                "file_hash": {
                    "type": "string",
                    "example": "5427593514859b0701e8e12ecbce1b0b"
                },
                "group": {
                    "type": "string",
                    "example": "344"
                },
                "id": {
                    "type": "string"
                },
                "schedule": {
                    "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.NumeratorDenominatorSchedule"
                },
                "update_at": {
                    "type": "string"
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1
                    ]
                },
                "faculties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "фаиту",
                        "фвт"
                    ]
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "344",
                        "345"
                    ]
                },
                "lesson": {
                    "type": "string",
                    "example": "л.Высшая математика\nдоц.Конюхов А.Н.   333 С"
                },
                "time": {
                    "type": "string",
                    "example": "08.10-09.45"
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.TeacherSchedule": {
            "type": "object",
            "properties": {
                "schedule": {
                    "type": "object",
                    "properties": {
                        "denominator": {
                            "type": "object",
                            "properties": {
                                "friday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "monday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "saturday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "thursday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "tuesday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "wednesday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                }
                            }
                        },
                        "numerator": {
                            "type": "object",
                            "properties": {
                                "friday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "monday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "saturday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "thursday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "tuesday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                },
                                "wednesday": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson"
                                    }
                                }
                            }
                        }
                    }
                },
                "teacher": {
                    "type": "string",
                    "example": "Конюхов Алексей Николаевич,Маношкин Алексей Борисович"
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.TeachersList": {
            "type": "object",
            "properties": {
                "teachers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Конюхов Алексей Николаевич",
                        "Маношкин Алексей Борисович"
                    ]
                }
            }
        },
        "github_com_schedule-rsreu_schedule-api_internal_models.WeekSchedule": {
            "type": "object",
            "properties": {
                "friday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule"
                    }
                },
                "monday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule"
                    }
                },
                "saturday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule"
                    }
                },
                "thursday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule"
                    }
                },
                "tuesday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule"
                    }
                },
                "wednesday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule"
                    }
                }
            }
        },
        "internal_http_handlers_v1.schedulesByGroupsRequest": {
            "type": "object",
            "required": [
                "groups"
            ],
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "344",
                        "345",
                        "346"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Schedule API",
	Description:      "API for RSREU schedule.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
