definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.CourseFaculties:
    properties:
      course:
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        example: 1
        type: integer
      faculties:
        items:
          enum:
          - иэф
          - фаиту
          - фвт
          - фрт
          - фэ
          type: string
        type: array
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.Day:
    properties:
      day:
        enum:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday
        example: Monday
        type: string
      day_ru:
        enum:
        - Пн
        - Вт
        - Ср
        - Чт
        - Пт
        - Сб
        - Вс
        example: Пн
        type: string
      time:
        example: "08.10"
        type: string
      week_type:
        enum:
        - числитель
        - знаменатель
        example: знаменатель
        type: string
      week_type_eng:
        enum:
        - numerator
        - denominator
        example: numerator
        type: string
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule:
    properties:
      lesson:
        example: |-
          л.Высшая математика
          доц.Конюхов А.Н.   333 С
        type: string
      time:
        example: 08.10-09.45
        type: string
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.Faculties:
    properties:
      faculties:
        items:
          type: string
        type: array
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.FacultyCourses:
    properties:
      courses:
        items:
          type: integer
        type: array
      faculty:
        enum:
        - иэф
        - фаиту
        - фвт
        - фрт
        - фэ
        example: фвт
        type: string
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.NumeratorDenominatorSchedule:
    properties:
      denominator:
        $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.WeekSchedule'
      numerator:
        $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.WeekSchedule'
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.Schedule:
    properties:
      course:
        example: 1
        type: integer
      faculty:
        example: фвт
        type: string
      file:
        type: string
      file_hash:
        example: 5427593514859b0701e8e12ecbce1b0b
        type: string
      group:
        example: "344"
        type: string
      id:
        type: string
      schedule:
        $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.NumeratorDenominatorSchedule'
      update_at:
        type: string
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson:
    properties:
      courses:
        example:
        - 1
        items:
          type: integer
        type: array
      faculties:
        example:
        - фаиту
        - фвт
        items:
          type: string
        type: array
      groups:
        example:
        - "344"
        - "345"
        items:
          type: string
        type: array
      lesson:
        example: |-
          л.Высшая математика
          доц.Конюхов А.Н.   333 С
        type: string
      time:
        example: 08.10-09.45
        type: string
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.TeacherSchedule:
    properties:
      schedule:
        properties:
          denominator:
            properties:
              friday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              monday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              saturday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              thursday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              tuesday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              wednesday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
            type: object
          numerator:
            properties:
              friday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              monday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              saturday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              thursday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              tuesday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
              wednesday:
                items:
                  $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherLesson'
                type: array
            type: object
        type: object
      teacher:
        example: Конюхов Алексей Николаевич,Маношкин Алексей Борисович
        type: string
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.TeachersList:
    properties:
      teachers:
        example:
        - Конюхов Алексей Николаевич
        - Маношкин Алексей Борисович
        items:
          type: string
        type: array
    type: object
  github_com_schedule-rsreu_schedule-api_internal_models.WeekSchedule:
    properties:
      friday:
        items:
          $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule'
        type: array
      monday:
        items:
          $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule'
        type: array
      saturday:
        items:
          $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule'
        type: array
      thursday:
        items:
          $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule'
        type: array
      tuesday:
        items:
          $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule'
        type: array
      wednesday:
        items:
          $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.DayLessonSchedule'
        type: array
    type: object
  internal_http_handlers_v1.schedulesByGroupsRequest:
    properties:
      groups:
        example:
        - "344"
        - "345"
        - "346"
        items:
          type: string
        type: array
    required:
    - groups
    type: object
externalDocs:
  description: GitHub
  url: https://github.com/schedule-rsreu/schedule-api
info:
  contact: {}
  description: API for RSREU schedule.
  title: Schedule API
  version: "2.0"
paths:
  /api/v1/schedule/courses:
    get:
      description: Курсы факультета
      parameters:
      - description: faculty
        enum:
        - иэф
        - фаиту
        - фвт
        - фрт
        - фэ
        in: query
        name: faculty
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.FacultyCourses'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get faculty courses
      tags:
      - Courses
  /api/v1/schedule/day:
    get:
      description: Информация о текущем дне
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Day'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get day
      tags:
      - Day
  /api/v1/schedule/faculties:
    get:
      description: Факультеты
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Faculties'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get faculties
      tags:
      - Faculties
  /api/v1/schedule/faculties/course:
    get:
      description: Факультеты курса
      parameters:
      - description: course
        enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        in: query
        name: course
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.CourseFaculties'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get course faculties
      tags:
      - Faculties
  /api/v1/schedule/groups/{group}:
    get:
      description: Get schedule by group
      parameters:
      - description: group
        example: "344"
        in: path
        name: group
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Schedule'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get schedule by group
      tags:
      - Groups
  /api/v1/schedule/groups/sample:
    post:
      description: Рассписание для нескольких групп
      parameters:
      - description: groups
        in: body
        name: groups
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers_v1.schedulesByGroupsRequest'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.Schedule'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get schedules by groups
      tags:
      - Groups
  /api/v1/schedule/teachers:
    get:
      description: Расписание преподавателя
      parameters:
      - description: teacher
        example: '"Конюхов Алексей Николаевич"'
        in: query
        name: teacher
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeacherSchedule'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get teacher schedule
      tags:
      - Teachers
  /api/v1/schedule/teachers/all:
    get:
      description: Список всех преподавателей
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_schedule-rsreu_schedule-api_internal_models.TeachersList'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get teachers
      tags:
      - Teachers
swagger: "2.0"
